# Generated by Django 2.2.7 on 2019-11-28 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='data',
            new_name='date',
        ),
    ]
