# Generated by Django 2.2.7 on 2019-12-02 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='balance_type',
            new_name='event_type',
        ),
    ]
