# Generated by Django 2.2.7 on 2019-12-02 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191202_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='event_type',
        ),
    ]
